In [1]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=1)
model.evaluate(x_test, y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.1400 - accuracy: 0.9599


[0.14004063606262207, 0.9599000215530396]

In [ ]:
!unzip /content/archive.zip

unzip:  cannot find or open /content/archive.zip, /content/archive.zip.zip or /content/archive.zip.ZIP.


# install simpletransformers

In [2]:
!pip install simpletransformers


     |████████████████████████████████| 249 kB 34.2 MB/s 
     |████████████████████████████████| 1.8 MB 62.0 MB/s 
     |████████████████████████████████| 1.2 MB 62.0 MB/s 
     |████████████████████████████████| 6.6 MB 61.3 MB/s 
     |████████████████████████████████| 4.0 MB 57.1 MB/s 
     |████████████████████████████████| 10.1 MB 58.3 MB/s 
     |████████████████████████████████| 43 kB 2.4 MB/s 
     |████████████████████████████████| 325 kB 73.1 MB/s 
     |████████████████████████████████| 77 kB 6.7 MB/s 
     |████████████████████████████████| 895 kB 61.4 MB/s 
     |████████████████████████████████| 596 kB 53.6 MB/s 
     |████████████████████████████████| 181 kB 77.5 MB/s 
     |████████████████████████████████| 144 kB 73.8 MB/s 
     |████████████████████████████████| 63 kB 2.1 MB/s 
     |████████████████████████████████| 1.1 MB 48.6 MB/s 
     |████████████████████████████████| 212 kB 66.0 MB/s 
     |████████████████████████████████| 136 kB 72.5 MB/s 
     |█████████████

# import training set and test set

In [3]:
import pandas as pd
df_dataset = pd.read_csv('/content/tweet_dataset.csv')
df_dataset.head()

textID   sentiment       author  \
0  1956967341       empty   xoshayzers   
1  1956967666     sadness    wannamama   
2  1956967696     sadness    coolfunky   
3  1956967789  enthusiasm  czareaquino   
4  1956968416     neutral    xkilljoyx   

                                                text  \
0   i know  i was listenin to bad habit earlier a...   
1  Layin n bed with a headache  ughhhh...waitin o...   
2                Funeral ceremony...gloomy friday...   
3               wants to hang out with friends SOON!   
4   We want to trade with someone who has Houston...   

                                            old_text       aux_id  \
0  @tiffanylue i know  i was listenin to bad habi...  p1000000000   
1  Layin n bed with a headache  ughhhh...waitin o...   c811396dc2   
2                Funeral ceremony...gloomy friday...   9063631ab1   
3               wants to hang out with friends SOON!   2a815f151d   
4  @dannycastillo We want to trade with someone w...   82565a56d3   

  new_sentiment                                      selected_text  
0           NaN                                                NaN  
1      negative                                           headache  
2      negative                                             gloomy  
3      positive               wants to hang out with friends SOON!  
4       neutral  We want to trade with someone who has Houston ...

In [4]:
df_dataset_cleared = df_dataset.dropna().sample(frac=1).reset_index(drop=True)
print( len(df_dataset_cleared), len(df_dataset))
df_dataset_cleared.head()

27767 40000


textID  sentiment          author  \
0  1753790091    neutral        heathfox   
1  1963113263    sadness        irodeo77   
2  1694476924       love  MariahHoneyLee   
3  1963593403  happiness     CrazyK1tten   
4  1963749812    neutral       helladrea   

                                                text  \
0   Hey Mr Luketic! I don`t have your number to s...   
1  so wanted to go to the Basshunter concert toni...   
2   i think i been followin u 4 bout a week so ye...   
3  Having dinner at the crown at south moreton wi...   
4  Yrbook signing w/ evryone was fun, I`m gna mis...   

                                            old_text      aux_id  \
0  @robluketic Hey Mr Luketic! I don't have your ...  9edc84f90d   
1  so wanted to go to the Basshunter concert toni...  b5a5da9be4   
2  @Sixxjohn i think i been followin u 4 bout a w...  b1e8cc92c5   
3  Having dinner at the crown at south moreton wi...  b9644304b3   
4  Yrbook signing w/ evryone was fun, I'm gna mis...  b4083313e2   

  new_sentiment                                      selected_text  
0       neutral  Hey Mr Luketic! I don`t have your number to se...  
1      positive                                so so so wanted to.  
2       neutral  i think i been followin u 4 bout a week so yea...  
3       neutral  Having dinner at the crown at south moreton wi...  
4       neutral  Yrbook signing w/ evryone was fun, I`m gna mis...

In [5]:
df_dataset_cleared['new_sentiment'].value_counts()

neutral     11163
positive     8780
negative     7824
Name: new_sentiment, dtype: int64

## label encode to integer

In [6]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

In [7]:
label_num_array = le.fit_transform(df_dataset_cleared['new_sentiment'])
label_num_array[:10]

array([1, 2, 1, 1, 1, 1, 0, 2, 1, 0])

In [10]:
df_dataset_cleared['label_num'] = label_num_array
df_dataset_cleared.head()

textID  sentiment          author  \
0  1753790091    neutral        heathfox   
1  1963113263    sadness        irodeo77   
2  1694476924       love  MariahHoneyLee   
3  1963593403  happiness     CrazyK1tten   
4  1963749812    neutral       helladrea   

                                                text  \
0   Hey Mr Luketic! I don`t have your number to s...   
1  so wanted to go to the Basshunter concert toni...   
2   i think i been followin u 4 bout a week so ye...   
3  Having dinner at the crown at south moreton wi...   
4  Yrbook signing w/ evryone was fun, I`m gna mis...   

                                            old_text      aux_id  \
0  @robluketic Hey Mr Luketic! I don't have your ...  9edc84f90d   
1  so wanted to go to the Basshunter concert toni...  b5a5da9be4   
2  @Sixxjohn i think i been followin u 4 bout a w...  b1e8cc92c5   
3  Having dinner at the crown at south moreton wi...  b9644304b3   
4  Yrbook signing w/ evryone was fun, I'm gna mis...  b4083313e2   

  new_sentiment                                      selected_text  label_num  
0       neutral  Hey Mr Luketic! I don`t have your number to se...          1  
1      positive                                so so so wanted to.          2  
2       neutral  i think i been followin u 4 bout a week so yea...          1  
3       neutral  Having dinner at the crown at south moreton wi...          1  
4       neutral  Yrbook signing w/ evryone was fun, I`m gna mis...          1

## changing the dataset to the standard format of simpletransformer input

---



In [11]:
df_dataset_cleared[['text','label_num']].head()

text  label_num
0   Hey Mr Luketic! I don`t have your number to s...          1
1  so wanted to go to the Basshunter concert toni...          2
2   i think i been followin u 4 bout a week so ye...          1
3  Having dinner at the crown at south moreton wi...          1
4  Yrbook signing w/ evryone was fun, I`m gna mis...          1

In [13]:
train_df = df_dataset_cleared[['text','label_num']][:22000]
train_df.columns = ["text", "labels"]
eval_df = df_dataset_cleared[['text','label_num']][22000:]
eval_df.columns = ["text", "labels"]

In [14]:
train_df.head()

text  labels
0   Hey Mr Luketic! I don`t have your number to s...       1
1  so wanted to go to the Basshunter concert toni...       2
2   i think i been followin u 4 bout a week so ye...       1
3  Having dinner at the crown at south moreton wi...       1
4  Yrbook signing w/ evryone was fun, I`m gna mis...       1

In [15]:
from simpletransformers.classification import ClassificationModel, ClassificationArgs
import pandas as pd
import logging


logging.basicConfig(level=logging.INFO)
transformers_logger = logging.getLogger("transformers")
transformers_logger.setLevel(logging.WARNING)

# create bert three-classification model

In [16]:
# Optional model configuration
model_args = ClassificationArgs(num_train_epochs=1,overwrite_output_dir=True)

# Create a ClassificationModel
model = ClassificationModel(
    'bert',
    'bert-base-cased',
    num_labels=3,
    args=model_args
)

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/416M [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-base-cased were not used when initializing BertForSequenceClassification: ['cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at b

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/208k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/426k [00:00<?, ?B/s]

# training the model

In [17]:
# Train the model
model.train_model(train_df)

INFO:simpletransformers.classification.classification_utils: Converting to features started. Cache is not used.


  0%|          | 0/22000 [00:00<?, ?it/s]

INFO:simpletransformers.classification.classification_utils: Saving features into cached file cache_dir/cached_train_bert_128_3_2
/usr/local/lib/python3.7/dist-packages/transformers/optimization.py:309: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  FutureWarning,


Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Running Epoch 0 of 1:   0%|          | 0/2750 [00:00<?, ?it/s]

INFO:simpletransformers.classification.classification_model: Training of bert model complete. Saved to outputs/.


(2750, 0.6313221158114347)

# evaluation

In [18]:
# Evaluate the model
result, model_outputs, wrong_predictions = model.eval_model(eval_df)

result, model_outputs, wrong_predictions 

INFO:simpletransformers.classification.classification_utils: Converting to features started. Cache is not used.


  0%|          | 0/5767 [00:00<?, ?it/s]

INFO:simpletransformers.classification.classification_utils: Saving features into cached file cache_dir/cached_dev_bert_128_3_2


Running Evaluation:   0%|          | 0/721 [00:00<?, ?it/s]

INFO:simpletransformers.classification.classification_model:{'mcc': 0.6802931696745239, 'eval_loss': 0.5335880662837736}


({'eval_loss': 0.5335880662837736, 'mcc': 0.6802931696745239},
 array([[-0.67626953,  2.03710938, -1.82910156],
        [-1.94433594,  2.3671875 , -0.51464844],
        [-1.81445312,  3.11914062, -1.40917969],
        ...,
        [-0.11151123,  1.26074219, -1.89257812],
        [-0.2668457 ,  0.75195312, -0.76660156],
        [ 2.6015625 , -0.84033203, -2.5390625 ]]),
 [{'guid': 3, 'text_a': ' forgot to answer your kindle question yesterday. honestly, haven`t used it much. have two paperback books i want 2 read first.', 'text_b': None, 'label': 0},
  {'guid': 9, 'text_a': 'i have to be at work at 5 am  ... thanks to me ppl will be getting their freakin starbucks. peace out ppls!', 'text_b': None, 'label': 1},
  {'guid': 12, 'text_a': ' I thought I was your best friend?', 'text_b': None, 'label': 1},
  {'guid': 17, 'text_a': 'Excellent the Suzaku 7 are back together  woop last episode  hope its a happy one i`m a sucker for these really lol shh', 'text_b': None, 'label': 2},
  {'guid': 

## get the result: predict_label

In [19]:
import numpy as np
predict_label = np.argmax(model_outputs,axis=1)
model_outputs,predict_label

(array([[-0.67626953,  2.03710938, -1.82910156],
        [-1.94433594,  2.3671875 , -0.51464844],
        [-1.81445312,  3.11914062, -1.40917969],
        ...,
        [-0.11151123,  1.26074219, -1.89257812],
        [-0.2668457 ,  0.75195312, -0.76660156],
        [ 2.6015625 , -0.84033203, -2.5390625 ]]),
 array([1, 1, 1, ..., 1, 1, 0]))

## get the classification report


In [20]:
from sklearn.metrics import classification_report

In [21]:
label_true = eval_df['labels']
label_true[:5]

22000    1
22001    1
22002    1
22003    0
22004    0
Name: labels, dtype: int64

In [22]:
print(classification_report(label_true, predict_label))

              precision    recall  f1-score   support

           0       0.79      0.78      0.79      1593
           1       0.76      0.75      0.76      2329
           2       0.82      0.84      0.83      1845

    accuracy                           0.79      5767
   macro avg       0.79      0.79      0.79      5767
weighted avg       0.79      0.79      0.79      5767



## save the result to .csv file

In [23]:
eval_df['predict_label'] = predict_label
eval_df

text  labels  \
22000  so yeah...i guess i dont get company this week...       1   
22001                                   Go get `em!  lol       1   
22002                                 Changing to work,.       1   
22003   forgot to answer your kindle question yesterd...       0   
22004   It`s Friday... But its only Friday morning. Ugh.       0   
...                                                  ...     ...   
27762   i can�t choose one  i love all the songs on...       2   
27763    hired all the smart monkeys for e-mail marke...       1   
27764  having to use IE =/ firefox is playing up and ...       1   
27765  _0 have you considered cordoning off a corner ...       1   
27766               Boys are stupid, throw rocks at them       0   

       predict_label  
22000              1  
22001              1  
22002              1  
22003              1  
22004              0  
...              ...  
27762              2  
27763              1  
27764              1  
27765              1  
27766              0  

[5767 rows x 3 columns]

In [24]:
eval_df.to_csv('predict_result.csv')

# run the model on the real dataset

In [25]:
project_dataset = pd.read_csv('/content/tweets.csv')
project_dataset.head()

tweet_id  original_tweet_id        date               source  \
0  1455116778531602433                NaN  2021-11-01      Twitter Web App   
1  1448617911912914947                NaN  2021-10-14   Twitter for iPhone   
2  1451893263775019010       1.451804e+18  2021-10-23   Twitter for iPhone   
3  1441086241450053641                NaN  2021-09-23  Twitter for Android   
4  1442906287193214982                NaN  2021-09-28  Twitter for Android   

  author_username                                 author_profile_url  \
0     clarkjbunch  https://pbs.twimg.com/profile_images/455739026...   
1     JudyCurtis1  https://pbs.twimg.com/profile_images/144826470...   
2     britchford9  https://pbs.twimg.com/profile_images/852981019...   
3     Le_Bilaiyaa  https://pbs.twimg.com/profile_images/140848710...   
4       sandyrnbc  https://pbs.twimg.com/profile_images/964713307...   

   verified_author                                               text  \
0            False  @TableJimmys Vaccine mandates are controversia...   
1            False  @yuhasz13 @OHLottery @OhioVax2School The numbe...   
2            False  The government is worried about the slow take ...   
3            False  @LekhakAnurag @coolfunnytshirt Vaccine working? 😂   
4            False  @MgRos48 @dotave @stolmeier @ChuckCallesto Nat...   

   id_unique      time lang       author_name  \
0     162214  10:17:29   en       Clark Bunch   
1     112965  11:53:18   en           JudyLou   
2     135842  12:48:23   en  Barry Britchford   
3      54562  17:05:08   en     Mohit מוהיט🇮🇳   
4      70405  17:37:21   en            Sandra   

                                  author_description media_keys  
0  Pastor (Unity Baptist) author (God is Near) hu...        NaN  
1  Married lady in Ohio who is here to keep up wi...        NaN  
2                                                NaN        NaN  
3                              💌\n\nUnfollowspy user        NaN  
4  Huge fan of Philadelphia Phillies, Eagles,  an...        NaN

In [33]:
project_dataset1 = project_dataset[:30000]
#project_dataset1.head()
project_dataset2 = project_dataset[30000:60000]
#project_dataset2.head()
project_dataset3 = project_dataset[60000:90000]
#project_dataset3.head()
project_dataset4 = project_dataset[90000:]

In [29]:
predictions1, raw_outputs1 = model.predict(list(project_dataset1['text']))

INFO:simpletransformers.classification.classification_utils: Converting to features started. Cache is not used.


  0%|          | 0/30000 [00:00<?, ?it/s]

  0%|          | 0/3750 [00:00<?, ?it/s]

In [31]:
predictions2, raw_outputs2 = model.predict(list(project_dataset2['text']))

INFO:simpletransformers.classification.classification_utils: Converting to features started. Cache is not used.


  0%|          | 0/30000 [00:00<?, ?it/s]

  0%|          | 0/3750 [00:00<?, ?it/s]

In [34]:
predictions3, raw_outputs3 = model.predict(list(project_dataset3['text']))

INFO:simpletransformers.classification.classification_utils: Converting to features started. Cache is not used.


  0%|          | 0/30000 [00:00<?, ?it/s]

  0%|          | 0/3750 [00:00<?, ?it/s]

In [35]:
predictions4, raw_outputs4 = model.predict(list(project_dataset4['text']))

INFO:simpletransformers.classification.classification_utils: Converting to features started. Cache is not used.


  0%|          | 0/10000 [00:00<?, ?it/s]

  0%|          | 0/1250 [00:00<?, ?it/s]

In [49]:
import numpy as np
predictions = np.append(predictions1, predictions2)
predictions = np.append(predictions, predictions3)
predictions = np.append(predictions, predictions4)


In [ ]:
project_dataset['predict_label'] = predictions
project_dataset

save to csv file

In [52]:
project_dataset.to_csv('sentiment_result.csv')

## import 200 labeled data for evaluation

In [53]:
dataset_200 = pd.read_csv('/content/labeled200.csv')
dataset_200.head()

tweet_id  original_tweet_id        date               source  \
0  1.460000e+18                NaN   2021/11/1      Twitter Web App   
1  1.450000e+18                NaN  2021/10/14   Twitter for iPhone   
2  1.450000e+18       1.450000e+18  2021/10/23   Twitter for iPhone   
3  1.440000e+18                NaN   2021/9/23  Twitter for Android   
4  1.440000e+18                NaN   2021/9/28  Twitter for Android   

  author_username                                 author_profile_url  \
0     clarkjbunch  https://pbs.twimg.com/profile_images/455739026...   
1     JudyCurtis1  https://pbs.twimg.com/profile_images/144826470...   
2     britchford9  https://pbs.twimg.com/profile_images/852981019...   
3     Le_Bilaiyaa  https://pbs.twimg.com/profile_images/140848710...   
4       sandyrnbc  https://pbs.twimg.com/profile_images/964713307...   

   verified_author                                               text  label  \
0            False  @TableJimmys Vaccine mandates are controversia...      1   
1            False  @yuhasz13 @OHLottery @OhioVax2School The numbe...      2   
2            False  The government is worried about the slow take ...      1   
3            False  @LekhakAnurag @coolfunnytshirt Vaccine working...      1   
4            False  @MgRos48 @dotave @stolmeier @ChuckCallesto Nat...      2   

  id_unique      time lang       author_name  \
0    162214  10:17:29   en       Clark Bunch   
1    112965  11:53:18   en           JudyLou   
2    135842  12:48:23   en  Barry Britchford   
3     54562  17:05:08   en   Mohit 诪讜讛讬讟馃嚠馃嚦   
4     70405  17:37:21   en            Sandra   

                                  author_description media_keys  
0  Pastor (Unity Baptist) author (God is Near) hu...        NaN  
1  Married lady in Ohio who is here to keep up wi...        NaN  
2                                                NaN        NaN  
3                             馃拰\n\nUnfollowspy user        NaN  
4  Huge fan of Philadelphia Phillies, Eagles,  an...        NaN

In [54]:
dataset_200['text']

0      @TableJimmys Vaccine mandates are controversia...
1      @yuhasz13 @OHLottery @OhioVax2School The numbe...
2      The government is worried about the slow take ...
3      @LekhakAnurag @coolfunnytshirt Vaccine working...
4      @MgRos48 @dotave @stolmeier @ChuckCallesto Nat...
                             ...                        
195    He's only gone cause it was on camera in front...
196    At Friday鈥檚 hearing before the CDC, doctors te...
197    @BreakfastNews NO! Covid still spreading in ot...
198    @JerKaphant @UndLaraKhar Get your vaccine, it'...
199    @JoyAnnReid So interesting because I just watc...
Name: text, Length: 200, dtype: object

## 模型预测

In [55]:
predictions, raw_outputs = model.predict(list(dataset_200['text']))

INFO:simpletransformers.classification.classification_utils: Converting to features started. Cache is not used.


  0%|          | 0/200 [00:00<?, ?it/s]

  0%|          | 0/25 [00:00<?, ?it/s]

In [56]:
predictions, raw_outputs 

(array([0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 2, 1, 1, 1, 0, 0, 0, 2, 1,
        1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 2, 2, 1, 1, 1, 1, 1,
        2, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 2, 0, 1, 1, 1, 1, 2, 1, 0,
        0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 2, 1, 2, 1, 1, 0, 1, 1, 1,
        1, 1, 2, 0, 0, 1, 1, 2, 1, 1, 0, 0, 0, 1, 1, 1, 1, 2, 1, 1, 0, 1,
        2, 1, 1, 1, 1, 0, 2, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 0, 1, 2, 2, 1,
        1, 2, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
        1, 2, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 2, 0, 0, 0, 2, 1, 0, 2, 0, 1,
        1, 2, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 2, 0, 1, 1, 1, 1, 0, 0,
        0, 2]), array([[ 4.09667969e-01,  2.79785156e-01, -1.32519531e+00],
        [ 6.56738281e-01,  6.42700195e-02, -1.52050781e+00],
        [ 2.32617188e+00, -6.18164062e-01, -2.72851562e+00],
        [-1.62988281e+00,  1.49023438e+00, -1.62963867e-01],
        [ 1.03027344e+00, -2.35443115e-02, -2.01562500e+00],
        [-1.71

In [57]:
dataset_200['predictions'] = predictions

dataset_200[['text','label','predictions']].head(10)

text  label  predictions
0  @TableJimmys Vaccine mandates are controversia...      1            0
1  @yuhasz13 @OHLottery @OhioVax2School The numbe...      2            0
2  The government is worried about the slow take ...      1            0
3  @LekhakAnurag @coolfunnytshirt Vaccine working...      1            1
4  @MgRos48 @dotave @stolmeier @ChuckCallesto Nat...      2            0
5  @longwoodjklcdn @fordnation You are the latest...      1            1
6  Doug Ford and Trudeau Canada steal our freedom...      0            1
7  2 Live Crew's Uncle Luke uses women's bodies a...      1            1
8  H.E @KagutaMuseveni "From animal feeds to ceme...      1            1
9  FOIA'd CDC Emails: Our Definition of Vaccine i...      0            0

## 分类报告

In [58]:
print(classification_report(dataset_200['label'], dataset_200['predictions']))

              precision    recall  f1-score   support

           0       0.35      0.45      0.39        49
           1       0.59      0.64      0.61       103
           2       0.56      0.29      0.38        48

    accuracy                           0.51       200
   macro avg       0.50      0.46      0.46       200
weighted avg       0.52      0.51      0.50       200

